### ISSUE TITLE
The Previous Styles Will Be Covered

### ISSUE THREAD

**Issue by qpxtWhite** [johnnybenson/sassr#14]
Here's my code:
```js
var cssBlue = require('./blue.scss'),
    cssRed = require('./red.scss');

cssBlue.append();
cssRed.append();
```
in 'blue.scss':
```css
.blue{color: blue;}
```
in 'red.scss
```css
.red{color: red;}
```
the code above will generate style in the page, and the cssBlue is lost:
```html
<style>
.red{color:red}
</style>
```
